# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Postgame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Postgame
  ## AWS
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSUserPoolsSignIn', '~> 2.6.13'
  pod 'AWSAuthUI', '~> 2.6.13'
  pod 'AWSS3', '~> 2.6.13'   # For file transfers
  pod 'AWSCognito', '~> 2.6.13'   #For data sync
  pod 'AWSDynamoDB', '~> 2.6.13'
  pod 'AWSAuthCore', '~> 2.6.13'
  pod 'AWSAPIGateway', '~> 2.6.13'
  pod 'AWSAppSync'
  ## Rreactive
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  ## Fabric
  pod 'Fabric'
  pod 'Crashlytics'
  ## UI
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  ## Mapbox
  pod 'Mapbox-iOS-SDK', '~> 4.1'
  ## Misc
  pod 'KeychainSwift', '~> 11.0'
  pod 'PhoneNumberKit'
  pod 'TextFieldEffects'

  target 'PostgameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostgameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
