# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Postgame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Postgame
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'AWSS3'
  pod 'AWSCore', '~> 2.6.13'
  pod 'AWSCognitoIdentityProvider', '~> 2.6.13'

  target 'PostgameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostgameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
